<?php
// Heading
$_['heading_title'] = 'Fondy';

// Tab
$_['tab_general'] = 'General settings';
$_['tab_order_status'] = 'Order status';
$_['tab_style'] = 'Style';

// Text
$_['text_edit'] = 'Edit module';
$_['text_payment'] = 'Payment';
$_['text_oplata'] = '<a onclick="window.open(\'http://fondy.eu/\');"><img src="view/image/payment/oplata.png" alt="Fondy" title="Fondy" style="border: 1px solid #EEEEEE;" /></a>';
$_['text_success'] = 'Settings updated';
$_['text_pay'] = 'Fondy';
$_['text_card'] = 'Credit Card';
$_['text_response_description'] = 'Error text:';
$_['text_oplata_order_status'] = 'Order status:';
$_['text_response_code'] = 'Error code:';
$_['text_payment_details'] = 'Fondy payment details';
$_['text_fondy_order_id'] = 'Fondy ID order';
$_['text_payment_id'] = 'ID payment';
$_['text_order_total'] = 'Order total';
$_['text_masked_card'] = 'Masked card number';
$_['text_order_status'] = 'Order status';
$_['text_order_last_tran_type'] = 'Last transaction type';
$_['text_charge_the_amount'] = 'Charge the hold amount';
$_['text_total'] = 'Enter the amount';
$_['text_refund'] = 'Refund';
$_['text_success_action'] = 'Success!';

// Entry
$_['entry_env'] = 'Environment';
$_['entry_merchant'] = 'Merchant ID';
$_['entry_secretkey'] = 'Secret key';
$_['entry_geo_zone'] = 'Geo Zone';
$_['entry_order_success_status'] = 'Order status after payment';
$_['entry_order_process_status'] = 'Order status in progress';
$_['entry_order_cancelled_status'] = 'Order status in cancelled';
$_['entry_order_reverse_status'] = 'Order status in refund';
$_['entry_currency'] = 'Currency';
$_['entry_payment_type'] = 'Payment Type';
$_['entry_common_type'] = 'Common';
$_['entry_preauth_type'] = 'Capture pre-purchase';
$_['entry_status'] = 'Status';
$_['entry_sort_order'] = 'Ordering:';
$_['entry_styles'] = 'Fondy Styles';
$_['entry_process_payment_type'] = 'Payment integration type';
$_['entry_redirect'] = 'Redirect to Fondy';
$_['entry_built_in_checkout'] = 'Built in checkout';
$_['entry_style_theme'] = 'Theme';
$_['entry_light'] = 'Light';
$_['entry_dark'] = 'Dark';
$_['entry_style_preset'] = 'Preset';

// Btn
$_['btn_capture'] = 'Capture';
$_['btn_preauth_reverse'] = 'Cancel pre-purchase';
$_['btn_reverse'] = 'Refund';

// Error
$_['error_permission'] = "You haven't permission !";
$_['error_merchant'] = 'Merchant ID are incorrect!';
$_['error_secretkey'] = 'Secret key are empty!';

// Tooltip
$_['tooltip_entry_status'] = 'Display Fondy in the list of payment methods on the site';
$_['tooltip_entry_environment'] = 'Select \'Test\' for testing Fondy';
$_['tooltip_entry_merchant'] = 'Can be found in the Fondy portal (section \'Merchant Settings\' → \'Technical settings\')';
$_['tooltip_entry_secretkey'] = 'Can be found in the Fondy portal (section \'Merchant Settings\' → \'Technical settings\')';
$_['tooltip_entry_process_payment_type'] = 'Select where the Fondy payment page will be displayed';
$_['tooltip_entry_payment_type'] = 'If you select \'' . $_['entry_preauth_type'] . '\' the order amount is blocked on the payer\'s card';
$_['tooltip_field_payment_id'] = 'Unique payment ID generated by FONDY payment gateway';
$_['tooltip_btn_preauth_reverse'] = 'Available only for the entire order amount';

$_['help_entry_environment'] = '<i class="fa fa-info-circle" aria-hidden="true"></i> You have been assigned <a href="https://docs.fondy.eu/docs/page/2/">test</a> <em>' . $_['entry_merchant'] . '</em> and <em>' . $_['entry_secretkey'] . '</em>';
?>